kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-mounted
spec:
  containers:
    - name: busybox
      image: k8s.gcr.io/e2e-test-images/busybox:1.29-1
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: secrets-in-az-keyvault
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-in-az-keyvault
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "retrieve-secrets-using-managed-identity"