apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-secret-as-variable
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: <CLIENT_ID> # Set the clientID of the user-assigned managed identity to use
    keyvaultName: <AZURE_KEY_VAUL_NAME> # Set to the name of your key vault    
    tenantId: <TENANT_ID> # The tenant ID of the key vault
    objects: |
      array:
        - |
          objectName: username
          objectAlias: username
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - secretName: credential                    # name of the Kubernetes secret object
    type: Opaque                              # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)
    data:
    - key: user                           # data field to populate
      objectName: username                    # name of the mounted content to sync; this could be the object name or the object alias
    
