apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: retrieve-secrets-using-managed-identity
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: <CLIENT_ID> # Set the clientID of the user-assigned managed identity to use
    keyvaultName: <AZURE_KEY_VAUL_NAME> # Set to the name of your key vault    
    objects: |
      array:
        - |
          objectName: mysecret
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty

    tenantId: <TENANT_ID> # The tenant ID of the key vault
